name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download dependencies
        run: go mod download -x

      - name: Test
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          verbose: true
